#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    conf.ecpp_setupbuild(id='controller', 
                         device='atmega8', arch='avr8')
    
    conf.env.append_value('DEFINES', 'F_CPU=8000000UL')

def build(bld):
    bld.ecpp_build(
        id= 'controller',
        source   = ['controller.cpp', 
                    'bsp.cpp', 
                    'ui.cpp', 
                    'font.cpp'],
        target   = 'controller.elf',
        features = 'cxx cxxprogram',  
        includes = ['.', '../common'],
    ) 
