#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    conf.ecpp_setupbuild(id='3in1-calibrator', 
                         device='atmega8', 
                         arch='avr8')
    
    conf.env.append_value('DEFINES', 'F_CPU=8000000UL')

def build(bld):
    bld.ecpp_build(
        id= '3in1-calibrator',
        source   = ['calibrator.cpp', 
                    'fit.cpp', 
                    'bsp.cpp', 
                    'globals.cpp',
                    '../common/protocol.cpp', 
                    ],
        target   = '3in1-calibrator.elf',
        features = 'cxx cxxprogram',  
        includes = ['.', '../common'],
    ) 
