#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    conf.ecpp_setupbuild(id='attiny13a', 
                         device='attiny13a', arch='avr8')
    
    conf.env.append_value('DEFINES', 'F_CPU=1000000UL')
    
    conf.ecpp_setupbuild(id='controller', 
                         device='atmega8', arch='avr8')
    
    conf.env.append_value('DEFINES', 'F_CPU=8000000UL')
def build(bld):
    bld.ecpp_build(
        id= 'attiny13a',
        source   = ['main.cpp'],
        target   = 'attiny13a.elf',
        features = 'cxx cxxprogram',  
        includes = ['.'],
    ) 

    bld.ecpp_build(
        id= 'controller',
        source   = ['controller.cpp'],
        target   = 'controller.elf',
        features = 'cxx cxxprogram',  
        includes = ['.'],
    ) 
