#! /usr/bin/env python
# encoding: utf-8

def options(opt):
    pass

def configure(conf):
    conf.load_tools('avr8')
  
def build(bld):
    bld.program(
        source   = 'main.cpp',
        target   = 'firmware.elf',
        device   =  'attiny2313',
        features = 'firmware cxxprogram',  
        includes = ['.', '..' ],
        defines  = ['F_CPU=7680000UL'],
        # cxxflags = ['-fwhole-program'],
    )  