#! /usr/bin/env python
# encoding: utf-8
TOP = '.'
  
def options(opt):
    opt.recurse(['../externals/ecpp'])

def configure(conf):
    conf.recurse(['../externals/ecpp'])
  
    conf.ecpp_setupbuild(id='dab-pc', platform='native')
    conf.env.append_value('CXXFLAGS', '-ftemplate-depth=10000')
    
def build(bld):
    bld.recurse(['../externals/ecpp'])

    bld.ecpp_build(
        id= 'dab-pc',
        source   = 'dab-test.cc',
        target   = 'dab-pc',
        features = 'cxx cxxprogram',
        includes = ['.', ],
    )  
