#! /usr/bin/env python
# encoding: utf-8
TOP = '.'
  
def options(opt):
    opt.recurse(['../externals/ecpp','src'])

def configure(conf):
    conf.recurse(['../externals/ecpp','src'])
  
def build(ctx):
    ctx.recurse(['../externals/ecpp','src'])
